name: Linux Build Dev - V8 and Node
concurrency:
  group: linux_build
  cancel-in-progress: true
on:
  # trigger manually
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: amithgeorge
  JAVET_V8_VERSION: 10.6.194.14
  JAVET_NODE_VERSION: 18.10.0

jobs:
  v8_node:
    name: Publish container image with V8 source and binaries and Node.js source and binaries
    runs-on: ubuntu-20.04
    steps:
      - name: Set the IMAGE_TAG environment variable
        run: |
          echo 'IMAGE_TAG=${{ env.DOCKERHUB_USERNAME }}/javet-linux-dev:v8-${{ env.JAVET_V8_VERSION }}_node-${{ env.JAVET_NODE_VERSION }}_shallow' >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build docker image
        run: |
          echo 'IMAGE_TAG is ${{ env.IMAGE_TAG }}'
          docker build \
            -t ${{ env.IMAGE_TAG }} \
            --build-arg JAVET_V8_VERSION=${{ env.JAVET_V8_VERSION }} \
            --build-arg JAVET_NODE_VERSION=${{ env.JAVET_NODE_VERSION }} \
            -f docker/linux-x86_64/base.Dockerfile .

      - name: Publish the docker image
        run: |
          docker push ${{ env.IMAGE_TAG }}
